api_platform:
  title: Test Technique Api Platform
  version: 1.0.0
  formats:
    jsonld:   ['application/ld+json']
    jsonhal:  ['application/hal+json']
    jsonapi:  ['application/vnd.api+json']
    json:     ['application/json']
    json_merge_patch: ['application/merge-patch+json', 'application/json']

  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header



